Repository allanegidio/elixir_release, pull requests merged in 2023-01, with the labels that each got.

#1 add test commit
  lib/elixir_release_web/controllers/page_controller.ex
Labels: feature

#2 Automated notes
  .github/release.yml
  bar.md
  mix.exs
Labels: enhancement, Semver-Major

#5 test tag
  README.md
Labels: 24.2.0

#6 tag 2
  README.md
Labels: 24.2.0

#7 tag
  README.md
Labels: 24.2.1

#9 Update bar.md
  bar.md
Labels: feat

#8 Update foo.md
  foo.md
Labels: feature
